version: 1
jobs:
  build:
    docker:
      # Use the same Docker base as the project
      - image: nginx:latest
    working_directory: ~/repo
    steps:
      - run:
          name: install dependencies
          command: |
            # Install hadolint
            #sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            #sudo chmod +x /bin/hadolint

      # run tests!
      - run:
          name: run tests
          command: |
            make test
      # run lints!
      - run:
          name: run lint
          command: |
            make lint
